//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace orderLunch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public productDetail()
        {
            this.requestLists = new HashSet<requestList>();
        }
    
        public int menuId { get; set; }
        public int productId { get; set; }
        public string nameOfProduct { get; set; }
        public string Price { get; set; }
    
        public virtual MenuInfo MenuInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<requestList> requestLists { get; set; }
    }
}
